### ISSUE TITLE
Visual Sudio build exe error with LuaMinify: " C2026: string too big..."

### ISSUE THREAD

**Issue by ngocgodwar** [pigpigyyy/MoonPlus#10]
I build with Visual Sudio 2019 failed and get these errors:
...\src\LuaMinify.h(661,1): error C2026: string too big, trailing characters truncated
...\src\LuaMinify.h(1332,1): error C2026: string too big, trailing characters truncated
...\src\LuaMinify.h(1898,1): error C2026: string too big, trailing characters truncated

Could you take a look at it?
Many thanks and regards!

**Comment by pigpigyyy** [comment]
Fixed by 45394b86b759ff1ac9f14e0e19dc6675167b2102.

**Comment by ngocgodwar** [comment]
Confirm Fixed!

Many thanks and regards!
