### ISSUE TITLE
Use "global" with table withoud {} error!

### ISSUE THREAD

**Issue by ngocgodwar** [pigpigyyy/MoonPlus#11]
The code below:
```moonscript
global backpack =
	something:
		yeah: 200
		they: ->
			print "hello"
			yor_feet"small"
		pretty: hair
		gold: hmm
	yow: 1000

	eat: goo
	yeah: dudd

start =
	something: "cold"

global bathe =
	on: "fire"
```

compile throw error:
```
1: syntax error
global backpack =
                 ^
```

Can you check it out?
Many thanks and regards!

**Comment by pigpigyyy** [comment]
003732436b1722a65731b2ba9e67074b91a71e73 Should fix this problem. It's the lack of syntax support from original Moonscript compiler. Only assignment statement allows table block placed in the right part, but adding such syntax won't cause any conflict.

**Comment by ngocgodwar** [comment]
Confirm Fixed!
