### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by CriztianiX** [pigpigyyy/MoonPlus#16]
Hello, I am thinking of making a new product leaving moonscript behind and starting with moonplus.
Moonplus can be considered 'Production Ready'?

**Comment by pigpigyyy** [comment]
MoonPlus is a new project with few users. I'm using MoonPlus in some of my game projects and got it tested with 30K lines of Moonscript codes until now by myself. But there are still some syntax cases not being tested so far, especially for some new MoonPlus features combined with all kinds of possible syntax with old Moonscript. You can have a try with MoonPlus and issue me whenever possible.
