### ISSUE TITLE
Pipeline Without Backslash

### ISSUE THREAD

**Issue by turbo** [pigpigyyy/MoonPlus#18]
Would it be possible to change the syntax of

```moon
{1,2,3} \
  |> map((x)-> x * 2) \
  |> filter((x)-> x > 4) \
  |> reduce(0, (a,b)-> a + b) \
  |> print
```

to not require a `\` at the end? Subjectively, it doesn't feel very moonscripty to have to terminate a line. See also [livescript](https://livescript.net/) for similar syntax.

**Comment by pigpigyyy** [comment]
Have been thinking about removing backslash to escape new line for a while. Just made a commit to write multiline expression with binary operators and got it tested with existing test cases. Please check it out cb5371a7dcfde196db07f5a2a3f144888b73d522

**Comment by turbo** [comment]
Amazing! Thanks! Look a lot cleaner, and keeping parens around multiline invocation is much more readable.
