### ISSUE TITLE
Merge tables with destructuring

### ISSUE THREAD

**Issue by CriztianiX** [pigpigyyy/MoonPlus#22]
It would be very interesting if we can have some kind of destructuring like js has.

```
const obj1 = { a:1, b1: 1 }
const obj2 = { a:2, b2: 2}
const obj3 = {...obj1, ...obj2}
```

```
{
    a1: 1,
    b1: 1,
    a2: 2,
    b2: 2
}
```

**Comment by ngocgodwar** [comment]
MoonPlus compile to Lua. Lua {} != JS {}. Lua has table.unpack is close but not equal to JS "...". And we can only add syntax sugar, no magic to MoonPLus compiler.
Any thing that so specific like above "a -> a1, a2" should easy implement in user code, it not wise to pack it compiler. 

Thanks and regards.

**Comment by pigpigyyy** [comment]
MoonPlus is a transpiler generating Lua codes. The only way to support this syntax has to be this way.
```Moonscript
const obj1 = {a1: 1, b1: 1}
const obj2 = {a2: 2, b2: 2}
const obj3 = {a3: 2, b3: 2}
const obj4 = {...obj1, ...obj2, ...obj3}
```
compiled to
```Lua
local obj1 <const> = {a1 = 1, b1 = 1}
local obj2 <const> = {a2 = 2, b2 = 2}
local obj3 <const> = {a3 = 2, b3 = 2}
local obj4 <const> = {}
for k, v in pairs(obj1) do
  obj4[k] = v
end
for k, v in pairs(obj2) do
  obj4[k] = v
end
for k, v in pairs(obj3) do
  obj4[k] = v
end
```
How about writing a helper function to serve the same purpose instead of inserting lots of codes by the transpiler?
```Moonscript
mix = (...)->
  t = {}
  tbs = {...}
  for tb in *tbs
    for k, v in pairs tb
      t[k] = v
  t

const obj1 = {a1: 1, b1: 1}
const obj2 = {a2: 2, b2: 2}
const obj3 = {a3: 2, b3: 2}
const obj4 = mix obj1, obj2, obj3
```

**Comment by CriztianiX** [comment]
Sounds good, thanks
