### ISSUE TITLE
Add a build target for moonp.so

### ISSUE THREAD

**Issue by megagrump** [pigpigyyy/MoonPlus#23]
I can't use luarocks and want to build `moonp.so` manually, but the makefile does not seem to support this.

**Comment by pigpigyyy** [comment]
Build target added, you can now build moonp.so file with command `make shared LUAI=/usr/local/include/lua LUAL=/usr/local/lib/lua`, see 1afca4888b2ee8e49c2e4d0bef478d0728d5ed41

**Comment by megagrump** [comment]
Nice, thank you.
