### ISSUE TITLE
Add support create table include order/unordered items without brackets like LiveScript!

### ISSUE THREAD

**Issue by ngocgodwar** [pigpigyyy/MoonPlus#24]
Exam:
```LiveScript
heroine =
  name: "Christina"
  age: 18
  job: "Princess"
  likes:
    * "kittens"
    * "flower"
  items:
    * "ring"
    * "necklace"
  status:
    * "weak"
    health: 50
    mana: 100
```
It will look more clearer without open and close bracket.

And one more thing. Can we backtick to quote raw string instead of double [[...]]. Only lua use [[...]] just look horrify and distracted.

Thanks and regards!

**Comment by pigpigyyy** [comment]
just read about LiveScript for table literal features, a better example can be
```Moonscript
heroine =
  name: "Christina"
  age: 18
  job: "Princess"
  likes:
    * name: "kittens"
      img: "/image/kittens.png"
    * name: "flower"
      img: "/image/flower.png"
  items:
    * name: "ring"
      amount: 2
    * name: "necklace"
      amount: 1
  status:
    desc: "weak"
    * attribute: "health"
      value: 50
    * attribute: "mana"
      value: 100
```
could be more readable than
```Moonscript
heroine =
  name: "Christina"
  age: 18
  job: "Princess"
  likes: {
    {
        name: "kittens"
        img: "/image/kittens.png"
    }
    {
        name: "flower"
        img: "/image/flower.png"
    }
  }
  items: {
    {
        name: "ring"
        amount: 2
    }
    {
        name: "necklace"
        amount: 1
    }
  }
  status: {
    desc: "weak"
    {
      attribute: "health"
      value: 50
    }
    {
      attribute: "mana"
      value: 100
    }
  }
```
I'm working on it adding the new feature.

**Comment by pigpigyyy** [comment]
Livescript uses backtick for infix function call and insert raw js codes into LiveScript codes. And I'm not seeing many other languages use backtick for quoting raw string. So maybe it's better to be consistent with Lua syntax could be a better choice.

**Comment by CriztianiX** [comment]
Any progress about this feature?

**Comment by pigpigyyy** [comment]
Feature added. See 7b2cf4ca35d8741490f806163f0f5dea56610e02 or 85b9ec82247f6e06b802188af35d09d3159625df, feature implemented in new multiline expression rules and old rules.

**Comment by CriztianiX** [comment]
Great! Why is not merged into master?

**Comment by pigpigyyy** [comment]
Still failing to decide how the multiline expression rules should be. See #25

**Comment by pigpigyyy** [comment]
> Great! Why is not merged into master?

Still failing to decide how the multiline expression rules should be. See #25

**Comment by pigpigyyy** [comment]
Merged into master with the old Moonscript multiline rule. And implicit object now starts with * symbol.

**Comment by CriztianiX** [comment]
Awasome feature!

**Comment by ngocgodwar** [comment]
Awasome! It is very nice addition for MoonPlus!

But right now it kind of limit only support * symbol with table after.
Can you make it support widely other thing than only table? EX:
```MoonScript
inventory =
  * "sword"
  * "shield"
  * name: "position"
    count: 10
  * name: "bread"
    count: 3
```

Thanks and regards!

**Comment by pigpigyyy** [comment]
> Awasome! It is very nice addition for MoonPlus!
> 
> But right now it kind of limit only support * symbol with table after.
> Can you make it support widely other thing than only table? EX:
> 
> ```moonscript
> inventory =
>   * "sword"
>   * "shield"
>   * name: "potion"
>     count: 10
>   * name: "bread"
>     count: 3
> ```
> 
> Thanks and regards!

OK, add feature with 5b656d2913e4f9f0017698ec835ce4ddda1dc81f
But putting different stuff into an array table could be a bad practice for Lua. A better example could be
```moonscript
inventory =
  equipments:
    * "sword"
    * "shield"
  items:
    * name: "potion"
      count: 10
    * name: "bread"
      count: 3
```
Compiles to
```Lua
local inventory = {
  equipments = {
    "sword",
    "shield"
  },
  items = {
    {
      name = "potion",
      count = 10
    },
    {
      name = "bread",
      count = 3
    }
  }
}
```

**Comment by ngocgodwar** [comment]
Awasome & Thanks!
