### ISSUE TITLE
Error when call function with multi anonymous functions as paramters!

### ISSUE THREAD

**Issue by ngocgodwar** [pigpigyyy/MoonPlus#25]
Error when call function with multi anonymous functions as paramters. EX:

* CASE 1:
```MoonScript
f x,
  -> a,
  -> b,
  -> c
```

MoonScript =>
```Lua
return f(x, function()
  return a
end, function()
  return b
end, function()
  return c
end)
```

MoonPlus =>
```Lua
return f(x, function()
  return a, function()
    return b, function()
      return c
    end
  end
end)
```

* CASE 2:
```MoonScript
f x,
  ->
    a,
  ->
    b,
  ->
    c
```

MoonScript =>
```Lua
return f(x, function()
  return a
end, function()
  return b
end, function()
  return c
end)
```

MoonPlus =>
```
Fail to compile: ...
3: expression list is not supported here
    a,
^
```

Is it intended behavior? Can you check it out!
Thanks and regrads.

**Comment by pigpigyyy** [comment]
Expression list written in multi-line is not supported in Moonscript.
```Moonscript
-- in moonscript
f = -> a,
  -> b
-- will cause error Failed to parse: [1] >>    f = -> a,

-- in MoonPlus, multi-line expression list is enabled and will be matched from right to left
f = -> a,
  -> b, 
  -> c

-- is equivalent to
f = -> a, (-> b, ( -> c))

-- to generate the same Lua codes in Moonscript for
f x,
  -> a,
  -> b,
  -> c

-- we have to write codes like
f x,
  (-> a),
  (-> b),
  (-> c)

-- or

f(x
  -> a
  -> b
  -> c
)

-- So in order to generate the same results from Moonscript
-- we have to disable the multi-line expression list behavior in MoonPlus
```
Do you think MoonPlus should go back to the original behavior or do some workaround for it?

**Comment by ngocgodwar** [comment]
Well... I would prefer old MoonScript have a multi-line anonymous functions as parameters behavior when call function as it look more clearer.

But I think MoonScript already have a workaround for that probrem.
As current, ";" has been used to denotes when function return values end in assignment statement.
```MoonScript
x = -> a;
  -> b;
  -> c
```
Then why we not use it in call function with multi-line parameters?
```MoonScript
x = -> a;
  -> b;
  -> c
```

What do you think?
Thanks and regrads.

**Comment by pigpigyyy** [comment]
Moonscript syntax is using semi coma to separate argument list from expression list.
```Moonscript
-- in Moonscript
a, b, c = 1; 2; 3 -- yes
f 1; 2; 3 -- no, function arguments must be separated with comas
x, y = f 1, 2; 3; 4 -- yes, equivalent to `x, y = f(1, 2), 3, 4` instead of `x, y = f(1, 2, 3, 4)`
-- so supporting the syntax below will break existing rules
f x,
  -> a;
  -> b;
  -> c
```

**Comment by ngocgodwar** [comment]
Well... It look like out option is just go back to the original behavior or not.

Ex:
```MoonScript
ajax url,
  (data) ->
    process data,
  (error) ->
    print error
```
VS
```MoonScript
ajax url,
  (data) ->
    process data, (error) ->
      print error
```
In that case call function, it seem like return to original behavior make more sense in MoonPlus.

What do you think?
Thanks and regrads.

**Comment by pigpigyyy** [comment]
I pushed two branches for the issue. One 75b9121054bd74cad0fec64013616436303bf479 continues making breaking changes for Moonscript that removes the complex multiline rules for function argument and makes the multiline rules more consist. The other one eba73a696c65932534fd5aefbe2ca4c7260c0fb6 reverts codes that breaks the original Moonscript rules. Digging around the Moonscript syntax a little more, I found in Moonscript's design adding multiline support for assignment list in the right side or expression list in the return statement will conflict with function argument rules.

There are some complex function argument syntax in Moonscript:
```Moonscript
hello 1,
  world 2,
    3,
    4

hello 1,
  world 2,
    3,
  4

f1 f2 2, f3 3, f4 4

f1 f2 2,
  f3 3,
  f4 4
```
Compiled in original Moonscript:
```Lua
hello(1, world(2, 3, 4))
hello(1, world(2, 3), 4)
f1(f2(2, f3(3, f4(4))))
f1(f2(2, f3(3), f4(4)))
```
Compiled in MoonPlus with new multiline rules:
```Lua
hello(1, world(2, 3, 4))
hello(1, world(2, 3, 4))
f1(f2(2, f3(3, f4(4))))
f1(f2(2, f3(3, f4(4))))
```
I think writing codes with brackets can be more expressive than writing codes with indents, special syntax in Moonscript can be written as:
```Moonscript
hello 1,
  world 2,
    3,
    4

hello 1,
  world(2,
    3),
    4

f1 f2 2, f3 3, f4 4

f1 f2(2), f3(3), f4(4)
```
If we are going to keep the original syntax, then we have to add back the escape new line symbol to concat some multiline expression lists in order not to get conflict with function argument rules, like:
```Moonscript
f = ->
  a, b, \
  c, d, \
  e, f

a, b, c, d = 1, \
  2, \
  3, \
  4

-- so that function argument can keep the same syntax
f a, b,
  c, d,
  e, f
```
I feel that the old argument indent syntax is not a good design and may lead to some confusion. Do you think we should go back to the original way or make some changes for it?

**Comment by ngocgodwar** [comment]
As I can see:
  + MoonScript limit support multiple lines arguments in some contexts that make sense
  + MoonPlus aim to consist support wide multiple lines

Well... old MoonScript only support multiple lines arguments list that take advance with significant meaning for level indentation and line break
```MoonScript
-- Arguments to a function can span across multiple lines as long as the
-- arguments are indented. The indentation can be nested as well.

my_func 5, -- called as my_func(5, 8, another_func(6, 7, 9, 1, 2), 5, 4)
    8, another_func 6, 7, -- called as
        9, 1, 2,          -- another_func(6, 7, 9, 1, 2)
    5, 4

-- If a function is used at the start of a block, the indentation can be
-- different than the level of indentation used in a block:

if func 1, 2, 3, -- called as func(1, 2, 3, "hello", "world")
        "hello",
        "world"
    print "hello"
```
And old MoonScript not support return statement multilines at all. Return must be one line. EX:
```MoonScript
-- Valid in new MoonPlus but not in old MoonScript
a,
b
```
```MoonScript
-- Valid in new MoonPlus but not in old MoonScript
return 1,
2
```
And:
```MoonScript
-- Valid in new MoonPlus but not in old MoonScript
return 1,
2
```
```MoonScript
a b,
c
-- MoonPlus: return a(b), c
-- MoonScript: Failed to parse: [1] >>    a b,
```
```MoonScript
a b,
  c
-- MoonPlus: return a(b, c)
-- MoonScript: return a(b, c)
```

In Summary
Old MoonScript just limit support multiple lines arguments so only small case to cover.
MoonScript kind of make try the most out of common use case and ignore the rest.
New MoonPlus widely limit support multiple lines so too much use case popup. Well, we can see some case just extreme to test behavior.

Without a doubt that code with with extra brackets more expressive than indents, but I kind of live MoonScript that try to remove brackets
```MoonScript
-- Work but kind of ugly
hello 1,
  world(2,
    3),
    4

-- Normal code will lo
hello 1,
  world(2, 3),
  4
-- or
hello 1,
  world 2, 3,
  4
-- or
hello 1,
  world 2,
    3,
  4
-- or extrem
hello 1,
  world 2,
    3,
    3.1, 3.2, 3.3, 3.4,
    3.5, 3.6, 3.7, 3.8,
  4
```

Well... old argument indent syntax is not a bad design because MoonScript only apply it limit for function call. But here we are MoonPlus, it kind of hard do decisive where to go here.

I think it will be the best if we can keep MoonScript support function call multiple lines arguments for forbackward compatibility while or other case follow MoonPlus rule.
But maybe some MoonPlus can introduce some fine control to let user choice which behavior they want. As MoonPlus grow and keep adding more features, some fine control options can be that way to please users both old MoonScript fan or new MoonPlus switcher.



What do you think?
Thanks and regrads.

**Comment by pigpigyyy** [comment]
Reverted to original Moonscript implementation in master branch to solve this problem.

**Comment by ngocgodwar** [comment]
MoonPlus now work as expected as MoonScript compiled!
Thanks and regrads.
