### ISSUE TITLE
Docker repository to keep updated images

### ISSUE THREAD

**Issue by CriztianiX** [pigpigyyy/MoonPlus#27]
Hello, i've created a dockerhub repository keepping updated images.
Can I share the credentials with you via private.

The dockerhub is:
https://hub.docker.com/r/moonplus/moonplus

Currently the repository has 3 images. 0.4.6, 0.4.9, 0.4.14
Maybe you can share this repository for all that users who want try moonp in easy way.

**Comment by pigpigyyy** [comment]
Just mentioned the docker hub in readme. How we can share the repo credentials? Maybe I can take time maintaining the docker repo along with the project.

**Comment by CriztianiX** [comment]
I will contact you in discord channel.

**Comment by CriztianiX** [comment]
I just shared the credentials via a private message on discord.
