### ISSUE TITLE
Can you add support table block syntax with nested order tables?

### ISSUE THREAD

**Issue by ngocgodwar** [pigpigyyy/MoonPlus#30]
New table block syntax is awesome but I hope it can support usefully feature like create nested tables.
Something like this:
```MoonScript
pairs =
  *
    * "king"
    * "queen"
  *
    * "hero"
    * "princess"
FAs =
  * * me
  * * beggar
  * * gamedev
```
Compile into Lua:
```Lua
local pairs =
{
  {
    "king",
    "queen"
  },
  {
    "king",
    "queen"
  }
}
local FAs =
{
  { "me" },
  { "beggar" },
  { "gamedev" }
}
```

Thanks and regards!

**Comment by pigpigyyy** [comment]
Syntax of
```Moonscript
pairs =
  *
    * "king"
    * "queen"
  *
    * "hero"
    * "princess"
```
is now supported, but implementing
```Moonscript
FAs =
  * * me
  * * beggar
  * * gamedev
```
could conflict with TableBlock syntax which must starts with new lines. We have to add new kinds of AST nodes and syntax to get this simple pattern implemented. I suggest using the consist way to write table blocks.

**Comment by ngocgodwar** [comment]
Many thanks and regards!
