### ISSUE TITLE
About file encoding?

### ISSUE THREAD

**Issue by ngocgodwar** [pigpigyyy/MoonPlus#37]
It look like MoonPlus can not handle file encoding utf8 with special characters...
Or may be windows build have that problem:
```moonscript
print "月+ = 🌙"
```
=>
```lua
return print("月+ = ")
```
Maybe I don't know but what encoding MoonPlus using or anyway to config that?

Can you check that?
Thanks and regards!

**Comment by pigpigyyy** [comment]
Found that used the wrong converter function from STL that can't handle special unicode character. Should be fixed by newest commit now.

**Comment by ngocgodwar** [comment]
confirmed!

Thanks!
