### ISSUE TITLE
About back call features new syntax

### ISSUE THREAD

**Issue by ngocgodwar** [pigpigyyy/MoonPlus#4]
I realy like new syntax. But I think it could be better with support indent to group functions like:
```moonscript
(data) <- http.get "ajaxtest"
    body[".result"]\html data
    (processed) <- http.post "ajaxprocess", data
        body[".result"]\append processed
        print "done"
```
i think it should be more visualize. What your thought above it?

**Comment by pigpigyyy** [comment]
Back call syntax is used to unnest callbacks to eliminate extra indents to do scoping.
```
do
	(data) <- http.get "ajaxtest"
	body[".result"]\html data
	(processed) <- http.post "ajaxprocess", data
	body[".result"]\append processed
	print "done"

-- and the codes above are equivalent to the codes below
-- If you prefer the way with indents, just write similar codes in callbacks

do
	http.get "ajaxtest", (data)->
		body[".result"]\html data
		http.post "ajaxprocess", data, (processed)->
			body[".result"]\append processed
			print "done"
```

**Comment by ngocgodwar** [comment]
Oh, I see! I just focus too much on new features. thanks very you much for explaining.
By the way, MoonPlus is an awesome projects, it address many issues of MoonScript. It have so much potential and if continue impove, it it will become popular in no time.
Thanks.
