### ISSUE TITLE
Maybe can improve macro feature...

### ISSUE THREAD

**Issue by ngocgodwar** [pigpigyyy/MoonPlus#6]
Hi!
I just test out marcro feature. It indeed very good addition for moonscript.
As I can see that MoonPlus tranfrom: $marcro => moonscript => lua script.

But I think it would be awesome if we can instruct $marcro transform directly to lua script. It would allow MoonPlus bypass many restriction of moonscript and use more many features of lua that moonscript won't allow like: goto, DSL, repeat...
What do you think?

Regards and many thanks!

**Comment by jagged-blades** [comment]
I agree with @ngocgodwar, not only for getting features not found in MoonPlus, but to also help make the compiler create more predictable and compatible Lua code.

**Comment by pigpigyyy** [comment]
I've being thinking of expanding macro to plain Lua codes. The main issue is how to validate the expanded codes at compile time since its a Moonscript compiler rather than a Lua compiler.  Maybe we can make use of the "load" function from Lua and precompile the expanded Lua codes to report errors before inserting them to the final codes.

**Comment by ngocgodwar** [comment]
I can see the many difficulties when mix blue with moonscript... 
Maybe we can have some flag that instruct macro insert lua code as it is without need validate.  Threre are many simple cases that really don't contribute much to script context and safe to just ignore it.
Let user take responsibility for what they write and MoonPlus don't need concern about it. 
Because as dynamic as lua is, many script context only make sense when in runtime. They are the nature of lua, and really nothing we can do about it.

There is project that simple just allow user to insert raw lua code as it is:
https://github.com/dmitrii-eremin/python-lua#insert-lua-code-in-the-python
What do you think?

Regards and many thanks!

**Comment by pigpigyyy** [comment]
The view about user should take responsibility for what they code makes sense. I just made a commit for this macro feature. And the Lua codes insertion feature is done with `luaL_loadbuffer()` to help early report Lua syntax issue before the code insertion.  The macro can now be used like:
```Moonscript
macro lua lua = (codes)-> "#{codes}"

x = 0

$lua [[
local function f(a)
  return a + 1
end
x = x + f(3)
]]

print x

macro lua def = (fname, ...)->
  args = {...}
  last = table.remove args
  "local function #{fname}(#{table.concat args, ', '})
  #{last}
end"

$def sel, a, b, c, [[
  if a then
    return b
  else
    return c
  end
]]

nil
```
compiles to codes:
```Lua
local x = 0
local function f(a)
  return a + 1
end
x = x + f(3)
print(x)
local function sel(a, b, c)
  if a then
    return b
  else
    return c
  end
end
return nil
```
We may further use this feature to write other languages inline Moonscript.
```Moonscript
macro lua xx_lang = (codes)->
  import "xx_lang"
  xx_lang.to_lua(codes)

$xx_lang[[
  ... -- codes of xx language
]]
```

**Comment by jagged-blades** [comment]
thanks for adding this in, however, there are a few problems or things to reconsider, e.g this code 
```
-- macro for creating labels. 
macro lua label = (name) -> "::#{name}::" 

-- macro to jump to label.
macro lua goto = (name) -> "goto #{name}"

local a = 0

-- 'start' label.
$label start

a += 1

if a == 5 
    -- when a is equal to 5, 
    -- it should jump to 'done' label, but instead a compiler error occurs. 
    $goto done 

-- jumps back to start label.
$goto start

-- 'done' label.
$label done

print ' (: '
```
triggers a compiler error:
```
Fail to compile: main.moon.
17: (macro goto):1: no visible label 'done' for <goto> at line 1
    $goto done 
    ^
```
This might be due to the 'luaL_loadbuffer()' function you showed in your example, since it didnt  evaluate the 'done' label yet, thus triggering the compiler error.

I removed some conditional checks for lua_loadbuffer() in moon_compiler.cpp:
```
if (luaL_loadbuffer(L, codes.c_str(), codes.size(), macroChunk.c_str()) != 0) {
                std::string err = lua_tostring(L, -1);
                throw std::logic_error(_info.errorMessage(err, x));
}
	return {nullptr, nullptr, std::move(codes)};
```
to just:
```
luaL_loadbuffer(L, codes.c_str(), codes.size(), macroChunk.c_str());
return {nullptr, nullptr, std::move(codes)};
```
and it seems that my code compiles correctly now:
```
Built main.moon
 (: 
```
not sure if there a flaw in my approach, though.

**Comment by pigpigyyy** [comment]
The problem can be better solved by adding goto statement support to Moonscript. Giving option to change the macro system behavior will load to different flavored users write codes in different standard, making it difficult to share or to integrate different code bases. The `luaL_loadbuffer()` check is to ensure the Lua code block inserted is a complete code block that makes `macro lua` works the same way like `macro block`.
Once goto statement support is added in Moonscript. We can just write:
```Moonscript
local a = 0
::start::
a += 1
if a == 5
  goto done 
goto start
::done::
```
Or without goto statement support. We can do it with:
```Moonscript
macro lua lua = (codes)-> "#{codes}"
local a = 0
$lua [[
::start::
a = a + 1
if a == 5 then
  goto done
end
goto start
::done::
]]
```

**Comment by pigpigyyy** [comment]
Similar problems for `macro block` exist. For example, these codes won't compile:
```Moonscript
macro block if = (cond,body)->
  "if #{cond}
  #{body}"

macro block else = (body)->
  "else
  #{body}"

$if flag, [[
  print "a"
]]
$else [[
  print "b"
]]
```
The right way to use `macro block` is:
```Moonscript
macro block if_else = (cond,body_if,body_else)->
  "if #{cond}
  #{body_if}
else
  #{body_else}"

$if_else flag,[[
  print "a"
]], [[
  print "b"
]]
```

**Comment by ngocgodwar** [comment]
I really like the idea to write raw lua or inline code in moonscript.
+1 for disable or enable error checks for lua macros is the best solution, it kind of treat it just like a text file.

Why and what use? Well... Why not? Consider it is just a plus and use only when need.
We can treat it as a work arround to remove all retrict of moonscript. It like work directly modify and insert code into result lua file when need.
Sometime I just want to keep comment to lua script, treat it as marker or whatever, make it read and debug result lua file more easier.

Now think about it. MoonPlus macro is supper awesome, it just like C preprocessor directives code modify dynamic + lua sript runtime dynamic.

Regards and many thanks!

**Comment by pigpigyyy** [comment]
Lua codes insertion without syntax check might not be a good design for a compiler. It could be hard for user to locate the syntax error in some codes and leaves compile time errors to be reported late at Moonscript's runtime.

**Comment by pigpigyyy** [comment]
The original Moonscript compiler ensures the Lua codes generated won't contain any Lua syntax issue, so I think it's better not to break this compiler behavior and make it simpler for users to track their coding problem.

**Comment by ngocgodwar** [comment]
I see, my head just go to far with the will idea.  We should keep language consistency  clean, simple and more express than introduce many confuse idea.
Let me close this.

Regards and many thanks!
