### ISSUE TITLE
Single statement ... if ... else error!

### ISSUE THREAD

**Issue by ngocgodwar** [pigpigyyy/MoonPlus#7]
I found that MoonPlus  compline single statement .. if ... else forget to handle value of else. As you can see:
```moonscript
s = "電子書"
length = string.len(s) if not utf8 else utf8.len(s)
print length
```
It compline to lua code:
```lua
local s = "電子書" -- 1
local length -- 2
if not utf8 then -- 2
	length = string.len(s) -- 2
else -- 2
	utf8.len(s) -- 2
end -- 2
return print(length) -- 3
```

And more here:
```moonscript
len = (o) ->
  return switch type(o)
    when 'string'
      utf8.len(o) if utf8 ~= nil else string.len(o)
    when 'table'
      #o
  nil, error "Invalid Type"

print len "電子書"
```
Turn in to:
```lua
local len -- 1
len = function(o) -- 1
	local _exp_0 = type(o) -- 2
	if 'string' == _exp_0 then -- 3
		if utf8 ~= nil then -- 4
			return utf8.len(o) -- 4
		else -- 4
			string.len(o) -- 4
		end -- 4
	elseif 'table' == _exp_0 then -- 5
		return #o -- 6
	end -- 6
	return nil, error("Invalid Type") -- 7
end -- 1
return print(len("電子書")) -- 9
```

Many thanks and regards!

**Comment by pigpigyyy** [comment]
The statement appendix syntax is transformed this way in Moonscript.

```Moonscript
statement if expr1 else expr2
-- transformed to
if expr1
  statement
else
  expr2
```
Just confirmed there is a difference between MoonPlus and original Moonscript compiler that needs to be fixed.
The original compiler:
```Moonscript
return f1! if true else f2!
return do f1! if true else f2!

a = f1! if true else f2!
b = do f1! if true else f2!
```
Compiles to:
```Lua
if true then
  return f1()
else
  f2()
end
do
  if true then
    return f1()
  else
    return f2()
  end
end
local a
if true then
  a = f1()
else
  f2()
end
local b
do
  if true then
    b = f1()
  else
    b = f2()
  end
end
```
MoonPlus compiles:
```Lua
if true then
  return f1()
else
  f2()
end
do
  if true then
    return f1()
  else
    f2()
  end
end
local a
if true then
  a = f1()
else
  f2()
end
local b
do
  if true then
    b = f1()
  else
    f2()
  end
end
```
But in your first case, the original Moonscript compiler still can't produce the expected results due to the way appendix syntax works. You can rewrite your codes to:
```Moonscript
s = "電子書"
length = if not utf8 then string.len(s) else utf8.len(s)
print length
```

**Comment by pigpigyyy** [comment]
And I have a thought the original Moonscript with if-else appendix for statement may be confusing. Think about the behaviors about these codes:
```Moonscript
return f1! if true else f2!
return do f1! if true else f2!
return if true then f1! else f2!

a = f1! if true else f2!
b = do f1! if true else f2!
c = if true then f1! else f2!
```
Maybe it's better to remove the "else" branch support for statement appendix to distinguish the usages.

**Comment by ngocgodwar** [comment]
Well... MoonScript is good but have many pitfalls and confuses on top of refuses to change and adapt. I understand his difficulties but that make MoonScript potential is waste.

As I can see many MoonScript feature take from CoffeeScript and Python. But... use if-else appendix as line decorator is really alienate concept.
At first glance, It look extract like Python if ... else statement inline or ternary op. But MoonScript call it is line decorator for a statement. It confuse as hell.

Any piece of code can be write in many ways, but if should expect consistency with languages.
Uhm... Just forget about any abstract concept. I can see that if-else appendix just a syntax sugar for if...else clause in a single line. Notthing more, Nothing less. So it should more sense to view as:
```moonscript
clause_true if condition else clause_false
-- transformed to
if condition
  clause_true
else
  clause_false
```
That mean one thing
```moonscript
res = clause_true if condition else clause_false
-- Should be the same
res = if condition
  clause_true
else
  clause_false
```
But MoonScript fail that, it conflict it self.

I think that not "else" cause but statement appendix concept it self is what really confuse. To the end it just syntax surgar.
Well... What you think?
Many thanks and regards!

**Comment by pigpigyyy** [comment]
The statement appendix has some special use case, though it's trivial. For example:
```Moonscript
-- this line hides variables 'fcolor' and 'message'
if fcolor = message\match "<%w*>" then message = message\gsub "<%->", fcolor

-- this line declares variable 'message' in scope, but hides 'fcolor'
message = message\gsub "<%->", fcolor if fcolor = message\match "<%w*>"
```
Compiles to:
```Lua
do
  local fcolor = message:match("<%w*>")
  if fcolor then
    local message = message:gsub("<%->", fcolor)
  end
end

local message
do
  local fcolor = message:match("<%w*>")
  if fcolor then
    message = message:gsub("<%->", fcolor)
  end
end
```

Since
```Moonscript
if condition then clause_true else clause_false
```
can privide similar functionality for the if-else line decorator. I think it's better to remove the `else` cause support but keep the if decorator to make things simpler. I've done the modification in commit aef3e34f15ca184722ea921d118e945461128886.

**Comment by ngocgodwar** [comment]
Agreed. If-else line decorator really not much of use in most cases. Let me close this.

Thanks and regards!
