### ISSUE TITLE
New uses for the 'in' keyword.

### ISSUE THREAD

**Issue by jagged-blades** [pigpigyyy/MoonPlus#8]
Suppose we have a list of numbers 1-10:
```
local list_of_numbers = {
    1, 2, 3, 4, 5
    6, 7, 8, 9, 10
}
```
How do we iterate through the list to find the number 5? 

Perhaps:
```
-- one of the current ways of doing searches for numbers. --

-- boolean checking if 5 is in the list.
local is_5_in_list = false

-- iterates through list to check is 5 exists.
for i in *list_of_numbers
    if i == 5
        is_5_in_list = true

        print '5 is in the list.'
        break

if not is_5_in_list
    print '5 is not in the list.'
```
Although this program works, I feel it is too verbose for such a simple goal. I suggest adding a feature that is found in languages like Python and Coffeescript:
```
-- new way of doing searches for numbers.
-- helps simplify the code and makes the code more understandable.
if 5 in list_of_numbers
    print '5 is in the list.'
else
    print '5 is not in the list.'
```
This is way cleaner IMO, and much more easier to understand.
Additionally, Syntax like:
```
-- helps turn some mult-line statements into one-liners.
print '5 is in the list.' if 5 in list_of_numbers
```
could be implemented making certain code much shorter and easier to understand.
Although these are small examples, I feel like larger projects could benefit from this by making the code more cleaner and elegant.

**Comment by ngocgodwar** [comment]
Well...  I would like to have an "in" op like Python... But I don't think it is a good idea with the way to create a temp local variable hold statue in mid of code with out a local scope to hide it.
And MoonScript is Lua, not Python and should not try to be when it can not. Lua table can be LIST and can be DICT at the same time, and can have metamethods so there are no universal "in" that fit all.
Programmer must write the code do what need in the context, it  can be function, meta method, lib or what ever...

Thanks and regards!

**Comment by pigpigyyy** [comment]
If you prefer writing inline codes instead of write function to achieve this. You can make use of the macro functions to implement similar syntax. For example:
```Moonscript
macro expr in = (target,list)-> "do
  local exist = false
  for item in *#{list}
    if item == #{target}
      exist = true
      break
  exist"

find = $in 5, {1,2,3,4,5}

if $in 5, {1,2,3,4,5}
  print "find"
```

**Comment by jagged-blades** [comment]
@pigpigyyy, Thanks a lot for the macro. I've reconsidered the idea, I think its better to not implement it, because of the possible ambiguity issues that could arise.
