### ISSUE TITLE
About existential operator behaviours?

### ISSUE THREAD

**Issue by ngocgodwar** [pigpigyyy/MoonPlus#9]
I just test existential as a clause:
```moonscript
len = utf8?.len or string?.len or (o) -> #o
```
It become:
```lua
local len -- 1
if utf8 ~= nil then -- 1
	len = utf8.len -- 1
end -- 1
```
Is it right?

Many thanks and regards!

**Comment by pigpigyyy** [comment]
Yes, it's a bug and I've got it fixed.

**Comment by pigpigyyy** [comment]
Just got too harried to make a fix for it and almost forgot, thank you for reporting the case!

**Comment by ngocgodwar** [comment]
I just checked. It fixed.

Many thanks and regards!
